global:
  pattern: secure-agent-workspace
  singleArgoCD: true
  sshPublicKey: ""
  secretLoader:
    disabled: false
main:
  clusterGroupName: prod
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*
