apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  configuration:
    developerConfiguration:
    {{- if .Values.softwareEmulation }}
      useEmulation: {{ .Values.softwareEmulation }}
    {{- end }}
