{{- if has "gmail" (.Values.secrets | default list) }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gmail
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStoreRef.name }}
    kind: {{ .Values.secretStoreRef.kind }}
  target:
    name: gmail
  dataFrom:
    - extract:
        key: {{ .Values.vaultPrefix }}/gmail
{{- end }}
