{{- if has "slack" (.Values.secrets | default list) }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStoreRef.name }}
    kind: {{ .Values.secretStoreRef.kind }}
  target:
    name: slack
  dataFrom:
    - extract:
        key: {{ .Values.vaultPrefix }}/slack
{{- end }}
