apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openshell-sandbox.fullname" . }}-prepare-scripts
  labels:
    {{- include "openshell-sandbox.labels" . | nindent 4 }}
data:
  {{- range $path, $_ := .Files.Glob "files/*.sh" }}
  {{ base $path }}: |
{{ tpl ($.Files.Get $path) $ | indent 4 }}
  {{- end }}
