#!/usr/bin/env python3
"""Fake systemctl: records the command, changes nothing."""
import json
import os
import sys
from pathlib import Path

with open(Path(os.environ["FAKE_STATE"]) / "systemctl.log", "a") as log:
    log.write(json.dumps(sys.argv[1:]) + "\n")
